version: '3.5'
services:
  notebook:
    volumes:
      - ./:/experiment/
      - /mnt/scratch/ssense/data_dumps/:/data
      - /mnt/scratch/ssense/models/:/models
    ports:
      - "9999:9999"
    build:
      shm_size: '8gb'
      context: .

  api:
    image: pgan-api
    build:
      shm_size: '8gb'
      context: .
      dockerfile: Dockerfile.api
    environment:
      MODEL_PATH: ${MODEL_PATH}
      MODELS_PATH: ${MODELS_PATH}
    env_file:
      - .env_api
    volumes:
      - /mnt/home/thomas/models_t_shirts/flat_models:/models
      - .:/src
    ports:
      - "5000:5000"
