# FROM nvcr.io/nvidia/tensorflow:18.09
FROM tensorflow/tensorflow:nightly-devel-gpu-py3
RUN mkdir /src
WORKDIR /src
COPY . /src

RUN pip install requirements-pip.txt
RUN pip install responder

CMD ["python", "api.py"]
